### ISSUE TITLE
Missing git tag 3.2.0

### ISSUE THREAD

**Issue by baloo** [webern/cargo-readme#61]
Hello!

Any chance you could push a tag 3.2.0 on cf66017c0120ae198210ebaf58a0be6a78372974. I believe cargo-readme has been pushed to crates.io but it's missing the git tag.

That makes it easier to package :)

Thank you!

**Comment by matthiasbeyer** [comment]
Bump

**Comment by baloo** [comment]
Hello fellow nixos co-maintainer ^^

**Comment by baloo** [comment]
Tag got published. Thank you!
