### ISSUE TITLE
Missing git tag 3.3.0

### ISSUE THREAD

**Issue by matthiasbeyer** [webern/cargo-readme#85]
The 3.2.0 tag [is also missing](https://github.com/webern/cargo-readme/issues/61) - now the 3.3.0 is missing as well.

We cannot even package the update in nixpkgs, because we don't know which commit the release was made from.

I would advise you yank the release on crates.io, because nobody is able to reproduce it, and create a new release 3.4.0 with a tag in this repository. Feel free to ping me then for updating the nixpkgs package.

**Comment by baloo** [comment]
(tag published)
